/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "on-tertiary-fixed": "#001d32",
                        "error-container": "#93000a",
                        "outline": "#a78b7d",
                        "on-secondary-container": "#b5b8c1",
                        "on-primary-fixed": "#341100",
                        "primary-fixed-dim": "#ffb690",
                        "on-tertiary-container": "#003554",
                        "tertiary-fixed": "#cde5ff",
                        "on-primary-fixed-variant": "#783200",
                        "surface-bright": "#45362f",
                        "secondary-container": "#454950",
                        "tertiary": "#93ccff",
                        "surface-variant": "#40322a",
                        "outline-variant": "#584237",
                        "tertiary-container": "#00a2f4",
                        "primary": "#ffb690",
                        "on-primary-container": "#582200",
                        "secondary": "#c3c6cf",
                        "surface": "#1c110b",
                        "inverse-on-surface": "#3c2d26",
                        "on-secondary-fixed-variant": "#43474e",
                        "secondary-fixed": "#dfe2eb",
                        "surface-tint": "#ffb690",
                        "secondary-fixed-dim": "#c3c6cf",
                        "surface-dim": "#1c110b",
                        "on-secondary-fixed": "#181c22",
                        "on-secondary": "#2d3137",
                        "on-background": "#f6ded3",
                        "on-tertiary-fixed-variant": "#004b74",
                        "surface-container-low": "#251913",
                        "inverse-primary": "#9d4300",
                        "error": "#ffb4ab",
                        "surface-container": "#291d16",
                        "tertiary-fixed-dim": "#93ccff",
                        "surface-container-high": "#352720",
                        "inverse-surface": "#f6ded3",
                        "surface-container-highest": "#40322a",
                        "background": "#050505",
                        "primary-container": "#F97316",
                        "on-primary": "#050505",
                        "on-tertiary": "#003351",
                        "on-surface": "#f6ded3",
                        "on-error": "#690005",
                        "on-error-container": "#ffdad6",
                        "primary-fixed": "#ffdbca",
                        "on-surface-variant": "#e0c0b1",
                        "surface-container-lowest": "#0D1117"
                    },
                    "borderRadius": {
                        "DEFAULT": "1rem",
                        "lg": "2rem",
                        "xl": "3rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "gutter": "24px",
                        "container-max": "1200px",
                        "section-gap-desktop": "160px",
                        "unit": "4px",
                        "margin-mobile": "20px",
                        "section-gap-mobile": "80px"
                    },
                    "fontFamily": {
                        "label-sm": ["Space Grotesk"],
                        "headline-lg-mobile": ["Space Grotesk"],
                        "headline-md": ["Space Grotesk"],
                        "display-xl": ["Space Grotesk"],
                        "body-md": ["Inter"],
                        "headline-lg": ["Space Grotesk"],
                        "body-lg": ["Inter"]
                    },
                    "fontSize": {
                        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
                        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
                        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
                        "display-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
                        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
                    }
                },
            },
  plugins: [],
}

